apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: hr-portal-http
  namespace: monitoring
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://<EXTERNAL_IP>
